In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier

In [2]:
input = np.random.randint(2, size=(1000, 5))
output = np.concatenate((input, input), axis=1)
noise = np.random.choice([0, 1], size=output.shape, p=[0.9, 0.1])
output = output ^ noise

In [3]:
cls = MultiOutputClassifier(LogisticRegression()).fit(input, output)

In [4]:
cls.predict_proba(input[:1])

[array([[0.11059612, 0.88940388]]),
 array([[0.91306318, 0.08693682]]),
 array([[0.89453918, 0.10546082]]),
 array([[0.84381452, 0.15618548]]),
 array([[0.89553827, 0.10446173]]),
 array([[0.13735844, 0.86264156]]),
 array([[0.88461529, 0.11538471]]),
 array([[0.91125561, 0.08874439]]),
 array([[0.90594328, 0.09405672]]),
 array([[0.87758163, 0.12241837]])]

In [5]:
input[:1]

array([[1, 0, 0, 0, 0]])